# Generated by Django 5.0.1 on 2024-01-08 13:08

import django.db.models.deletion
import mainApp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clubName", models.CharField(max_length=255)),
                (
                    "clubOrganiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="player",
            fields=[
                (
                    "playerName",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("inGameFlag", models.BooleanField(default=False)),
                ("elo", models.IntegerField(default=1200)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.club"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="session",
            fields=[
                ("sessionID", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField(default=mainApp.models.get_today)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.club"
                    ),
                ),
                ("players", models.ManyToManyField(to="mainApp.player")),
            ],
        ),
        migrations.CreateModel(
            name="match",
            fields=[
                ("matchID", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.CharField(default="00-00", max_length=255)),
                ("completed", models.BooleanField(default=False)),
                (
                    "team1",
                    models.ManyToManyField(related_name="team1", to="mainApp.player"),
                ),
                (
                    "team2",
                    models.ManyToManyField(related_name="team2", to="mainApp.player"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.session",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="club",
            constraint=models.UniqueConstraint(
                fields=("clubName", "clubOrganiser"), name="unique_club"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("sessionID", "club"), name="unique_session"
            ),
        ),
    ]
