# Generated by Django 5.0.1 on 2024-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
