# Generated by Django 5.0.1 on 2024-01-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("matchID", "session"), name="unique_match"
            ),
        ),
    ]
