# Generated by Django 5.0.1 on 2024-01-07 23:28

import mainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_alter_club_clubname_alter_club_cluborganiser"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="date",
            field=models.DateField(default=mainApp.models.get_today),
        ),
    ]
