# Generated by Django 5.0.1 on 2024-01-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0002_match_unique_match"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="loss",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="win",
            field=models.IntegerField(default=0),
        ),
    ]
