# Generated by Django 5.0.1 on 2024-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_alter_player_elo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="score",
            field=models.CharField(default="00-00", max_length=255),
        ),
    ]
