# Generated by Django 5.0.1 on 2024-01-07 23:58

import django.db.models.deletion
import mainApp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainApp", "0003_match_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="date",
        ),
        migrations.CreateModel(
            name="session",
            fields=[
                (
                    "date",
                    models.DateField(
                        default=mainApp.models.get_today,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("players", models.ManyToManyField(to="mainApp.player")),
            ],
        ),
        migrations.AddField(
            model_name="match",
            name="session",
            field=models.ForeignKey(
                default=mainApp.models.get_today,
                on_delete=django.db.models.deletion.CASCADE,
                to="mainApp.session",
            ),
        ),
    ]
